### ISSUE TITLE
generator-sqlops is not available

### ISSUE THREAD

**Issue by santiaago** [kevcunnane/sqlops-debug#1]
Hi, 

I was trying to install the extension generator but it seems `generator-sqlops` is not available at the moment..

```bash
> npm install -g yo generator-sqlops
npm ERR! code E404
npm ERR! 404 Not Found: generator-sqlops@latest
```

Thanks,

**Comment by SebastianPfliegel** [comment]
Have you checked again by now? It works for me. Which node/npm version are you running?

**Comment by santiaago** [comment]
It now works, I think it was registered in npm yesterday...

I noticed in npm there is now a [generator-sqlops package](https://www.npmjs.com/package/generator-sqlops) that points to https://github.com/llali/generator-sqlops

thanks for your help :)
