### ISSUE TITLE
Debugging on Linux

### ISSUE THREAD

**Issue by SebastianPfliegel** [kevcunnane/sqlops-debug#2]
VSCode: 1.22.1
SQLOps: 0.28.3
SQLOpsDebug: 1.0.2
OS: openSUSE Tumbleweed

If I try to debug without SQLOps is open (it's included in PATH though) this is the error message I receive:
```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:36251).
```

When I try to run the debugger when a SQLOps instance has been started:
```
Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue.
```

**Comment by kevcunnane** [comment]
Sorry for the (very extended) delay responding. We've seen a few issues succesfully starting the application. To resolve, we've changed the `timeout` to 30 seconds and if nothing seems to happen, manually opening SQL Operations Studio seems to launch the process successfully. I'm not sure why this isn't working on all systems and haven't had a chance to debug fully.

**Comment by kevcunnane** [comment]
So I've fixed the timeout issue and will open a new issue for tracking failure to launch on Windows. Closing this out for now
