### ISSUE TITLE
Can't connect to sqlops process

### ISSUE THREAD

**Issue by Ravatsaas** [kevcunnane/sqlops-debug#3]
## Steps to reproduce:

1. Generate a fresh extension boilerplate with `yo sqlops` (I selected Typescript extension)
2. Open project in VS Code
3. Hit F5

## Result

If I do this after a fresh reboot, and SqlOps is not already running I get this error in VS Code: 
"Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:33022)."

In this case, SqlOps is not launched, but the debug console in VS Code shows this: 
`C:\Program Files\SQL Operations Studio\sqlops.exe --debugBrkPluginHost=32226 --extensionDevelopmentPath=C:\work\sqlops-extensions\my-extension-name`

If an instance of SqlOps is already running, it opens another instance that has [Extension Development Host] in the title bar. VS Code now shows an error message that says "Operation Cancelled" SqlOps shows an error message that says "Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue"

## My environment:

Windows 10 Pro, Version 10.0.17134
Node v8.11.3
VS Code 1.25.1
SQL Operations Studio 0.31.4 (Also tried on 0.30.5 with same result)
SQL Operations Studio Debugger 1.0.2

**Comment by rtbenfield** [comment]
I have also been experiencing this issue with the same environment. It also occurred for me with the previous releases of SQL Operations Studio (0.30.x) and VS Code (1.24.x). The Developer Tools console in SQL Operations Studio prints `[Extension Host] STOPPED on first line for debugging on port 34067`, but VS Code does not seem to be attaching the debugger.

**Comment by kevcunnane** [comment]
Sorry for the  delay responding. We've seen a few issues successfully starting the application too, particularly on Windows. As mentioned it seems like having an instance open works around it, however the timeout of 10seconds is too low. To resolve, we've changed the `timeout` to 30 seconds as this gives the debugger enough time to connect.

**Comment by Ravatsaas** [comment]
That should do the trick. Thank you.

What's your release cadence? When should I expect to see this fix in the wild?

**Comment by dzsquared** [comment]
@kevcunnane this also occurs for me, I can work on extensions by selecting "start without debugging" - but obviously without the debugger it can be more difficult to chase down issues. I've poked around the code for the sql ops debug extension and can't locate the debugger attach timeout so I could repackage for development but I haven't been able to find it.  I'm guessing the timeout value is in sql operations studio?  If it's not, can you point me in the right direction so I can keep working on extensions? If it is - do you know when the fix might come to preview or release?
thank you!

**Comment by kevcunnane** [comment]
So - I've updated the default timeout to 30 seconds and released a new version of the extension. 

@dzsquared you could attach to SQL Ops after running "start without debugging" if this doesn't fix the issue by adding some timeout time. 

I'm going to close this issue and use #5 to track the issue where in Windows we need to click the app to launch debugger. I've an idea on how that might work but it needs more time to investigate. It's also possible that my pulling in upstream fixes solved it, but I am not expecting that to be the case.
